name: orderin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/orderin-100.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: SFRegular
      fonts:
        - asset: assets/fonts/SFUIDisplay-Regular.otf
    - family: SFBold
      fonts:
        - asset: assets/fonts/SFUIDisplay-Bold.ttf
